<a href="https://colab.research.google.com/github/Shivansh-Chaudhary/DSML_Project_MYANATOMY/blob/main/Pandasday2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
data={
    "Name":["Ajay", "Alex", "Arun", "Aman", "Anam"],
    "Age":[23,25,63,22,20]
}
#DataFrame
df = pd.DataFrame(data)
df.head()

   Name  Age
0  Ajay   23
1  Alex   25
2  Arun   63
3  Aman   22
4  Anam   20

In [ ]:
#read csv format
df = pd.read_csv("/content/sample_data/california_housing_test.csv")
df.head()
df.tail()
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           3000 non-null   float64
 1   latitude            3000 non-null   float64
 2   housing_median_age  3000 non-null   float64
 3   total_rooms         3000 non-null   float64
 4   total_bedrooms      3000 non-null   float64
 5   population          3000 non-null   float64
 6   households          3000 non-null   float64
 7   median_income       3000 non-null   float64
 8   median_house_value  3000 non-null   float64
dtypes: float64(9)
memory usage: 211.1 KB

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,3000.000000,3000.00000,3000.000000,3000.000000,3000.000000,3000.000000,3000.00000,3000.000000,3000.00000
mean,-119.589200,35.63539,28.845333,2599.578667,529.950667,1402.798667,489.91200,3.807272,205846.27500
std,1.994936,2.12967,12.555396,2155.593332,415.654368,1030.543012,365.42271,1.854512,113119.68747
min,-124.180000,32.56000,1.000000,6.000000,2.000000,5.000000,2.00000,0.499900,22500.00000
25%,-121.810000,33.93000,18.000000,1401.000000,291.000000,780.000000,273.00000,2.544000,121200.00000
50%,-118.485000,34.27000,29.000000,2106.000000,437.000000,1155.000000,409.50000,3.487150,177650.00000
75%,-118.020000,37.69000,37.000000,3129.000000,636.000000,1742.750000,597.25000,4.656475,263975.00000
max,-114.490000,41.92000,52.000000,30450.000000,5419.000000,11935.000000,4930.00000,15.000100,500001.00000

In [ ]:
#Selection of data
df['longitude'].head(10)
df[['longitude','latitude']].tail()

      longitude  latitude
2995    -119.86     34.42
2996    -118.14     34.06
2997    -119.70     36.30
2998    -117.12     34.10
2999    -119.63     34.42

In [ ]:
#selection of data by row wise
df.loc[0:5,'longitude':'latitude']

   longitude  latitude
0    -122.05     37.37
1    -118.30     34.26
2    -117.81     33.78
3    -118.36     33.82
4    -119.67     36.33
5    -119.56     36.51